apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.name" . }}-master
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if .Values.master.service.annotations }}
{{ toYaml .Values.master.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.master.service.type }}
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: {{ template "redis.name" . }}
    release: "{{ .Release.Name }}"
    {{- if .Values.cluster.enabled }}
    role: master
    {{- end }}
